import React, { useEffect, useState } from 'react';
import { BookOpen, Check, Copy, ExternalLink, Menu } from 'lucide-react';
import { Link } from 'react-router-dom';
import brandLogo from '../assets/logo.svg';

const baseUrl = 'https://ka-cards.com/client/api';
const navigation = [['introduction', 'Introduction'], ['base-url', 'Base URL'], ['authentication', 'Authentication'], ['profile', 'Profile'], ['products', 'Products'], ['product-fields', 'Product Fields'], ['content', 'Content / Categories'], ['create-order', 'Create Order'], ['check-orders', 'Check Orders'], ['status-values', 'Status Values'], ['errors', 'Error Codes'], ['code-examples', 'Code Examples'], ['legacy', 'Legacy Compatibility']];
const product = `[
  { "id": 1000, "name": "Example package", "price": 1.5, "currency": "USD", "available": true,
    "product_type": "package", "parent_id": 7, "category_name": "Example category", "category_img": "images/category/example.webp",
    "qty_values": null, "params": ["Player ID"],
    "fields": [{ "key": "player_id", "label": "Player ID", "type": "text", "required": true, "options": [] }] }
]`;
const checkResponse = `{
  "status": "OK", "data": [{ "order_id": "ID_0123456789abcdef", "order_uuid": "stable-client-key", "quantity": 1,
    "data": { "player_id": "123456789" }, "created_at": "2026-09-19 12:30:00", "product_name": "Example package",
    "price": "1.5", "status": "accept", "replay_api": null }]
}`;
const CopyButton = ({ value }) => { const [copied, setCopied] = useState(false); const copy = async () => { try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(value); else { const el = document.createElement('textarea'); el.value = value; el.style.cssText = 'position:fixed;opacity:0'; document.body.appendChild(el); el.select(); document.execCommand('copy'); el.remove(); } setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch { /* Selectable content remains available. */ } }; return <button type="button" onClick={copy} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-amber-300/35 bg-amber-300/10 px-3 py-2 text-xs font-semibold text-amber-100 hover:bg-amber-300/20 focus:outline-none focus:ring-2 focus:ring-amber-300/70" aria-label="Copy code">{copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}{copied ? 'Copied' : 'Copy'}</button>; };
const CodeBlock = ({ label = 'Example', children }) => { const value = String(children).trim(); return <div dir="ltr" className="overflow-hidden rounded-xl border border-slate-700/80 bg-[#090b16] text-left"><div className="flex items-center justify-between gap-3 border-b border-slate-700/80 bg-slate-900/70 px-3 py-2"><span className="font-mono text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</span><CopyButton value={value} /></div><pre className="max-w-full overflow-x-auto p-4 font-mono text-xs leading-6 text-slate-100 sm:text-[13px]"><code>{value}</code></pre></div>; };
const Section = ({ id, title, children }) => <section id={id} className="scroll-mt-24 rounded-2xl border border-slate-700/70 bg-[#121021] p-5 shadow-[0_18px_45px_rgba(0,0,0,.14)] sm:p-7"><h2 className="text-xl font-bold text-white sm:text-2xl">{title}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-slate-300">{children}</div></section>;
const Endpoint = ({ method, path, children }) => <article className="overflow-hidden rounded-xl border border-slate-700/70 bg-slate-950/40"><div className="flex flex-wrap items-center gap-2 border-b border-slate-700/70 bg-slate-900/50 px-4 py-3"><span className={'rounded-md px-2 py-1 font-mono text-xs font-bold ' + (method === 'POST' ? 'bg-amber-400/15 text-amber-100' : 'bg-emerald-400/15 text-emerald-200')}>{method}</span><code className="break-all font-mono text-sm font-semibold text-white">{path}</code></div><div className="space-y-4 p-4">{children}</div></article>;
const Nav = ({ active, mobile, close }) => <nav aria-label="API documentation sections" className={mobile ? 'grid gap-1 p-3' : 'space-y-1'}>{navigation.map(([id, label]) => <a key={id} href={'#' + id} onClick={close} className={'block rounded-lg px-3 py-2 text-sm transition ' + (active === id ? 'bg-amber-300/15 font-semibold text-amber-100' : 'text-slate-400 hover:bg-white/5 hover:text-white')}>{label}</a>)}</nav>;

export default function ApiDocs() {
  const [active, setActive] = useState('introduction');
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const item = entries.find((entry) => entry.isIntersecting); if (item) setActive(item.target.id); }, { rootMargin: '-18% 0px -72% 0px' }); navigation.forEach(([id]) => { const node = document.getElementById(id); if (node) observer.observe(node); }); return () => observer.disconnect(); }, []);
  const request = (path) => `GET ${baseUrl}${path}\napi-token: YOUR_API_TOKEN`;
  return <main dir="ltr" className="min-h-screen bg-[#090713] text-left text-slate-100"><header className="sticky top-0 z-40 border-b border-amber-200/15 bg-[#0d0a18]/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link to="/" className="flex min-w-0 items-center gap-3" aria-label="KA-CARD home"><span className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-amber-200/25 bg-amber-200/10"><img src={brandLogo} alt="KA-CARD" className="h-7 w-7 object-contain" /></span><span className="truncate text-sm font-bold tracking-wide text-white sm:text-base">KA-CARD API Documentation</span></Link><Link to="/developers/api" className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-amber-300/35 bg-amber-300/10 px-3 py-2 text-xs font-semibold text-amber-100"><span>API Management</span><ExternalLink className="h-3.5 w-3.5" /></Link></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8 lg:px-8"><details className="mb-5 rounded-xl border border-slate-700/70 bg-[#121021] lg:hidden"><summary className="flex cursor-pointer list-none items-center gap-2 px-4 py-3 text-sm font-semibold text-white [&::-webkit-details-marker]:hidden"><Menu className="h-4 w-4 text-amber-200" /> Browse sections</summary><div className="border-t border-slate-700/70"><Nav active={active} mobile close={(event) => event.currentTarget.closest('details')?.removeAttribute('open')} /></div></details><div className="grid items-start gap-8 lg:grid-cols-[230px_minmax(0,1fr)]"><aside className="hidden lg:block"><div className="sticky top-24 rounded-xl border border-slate-700/70 bg-[#121021]/80 p-3"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-wider text-slate-500">On this page</p><Nav active={active} /></div></aside><div className="min-w-0 space-y-6"><section className="rounded-2xl border border-amber-300/20 bg-[#151126] p-6 sm:p-8"><div className="flex items-center gap-2 text-sm font-semibold text-amber-100"><BookOpen className="h-4 w-4" /> Canonical B2B API v1</div><h1 className="mt-3 max-w-3xl text-3xl font-black tracking-tight text-white sm:text-4xl">Integrate with KA-CARD.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300 sm:text-base">Use your account API token with the canonical B2B endpoint. The server determines prices, validates the wallet, and controls fulfillment and order state.</p><div className="mt-6 rounded-xl border border-slate-700/80 bg-[#090b16] p-3 sm:flex sm:items-center sm:justify-between sm:gap-4"><div className="min-w-0"><p className="mb-1 text-xs font-bold uppercase tracking-wider text-slate-500">Base URL</p><code className="block overflow-x-auto whitespace-nowrap font-mono text-sm text-amber-100">{baseUrl}</code></div><div className="mt-3 sm:mt-0"><CopyButton value={baseUrl} /></div></div></section>
<Section id="introduction" title="Introduction"><p>Canonical product and category IDs are numeric compatibility IDs. Do not use internal MongoDB IDs in B2B integrations.</p></Section>
<Section id="base-url" title="Base URL"><p>This absolute URL already includes <code>/client/api</code>; append endpoint paths exactly once.</p><CodeBlock label="Canonical base URL">{baseUrl}</CodeBlock></Section>
<Section id="authentication" title="Authentication"><p>Send <code>api-token</code> on every request. The two supported aliases are shown for existing integrations.</p><CodeBlock label="Primary header">api-token: YOUR_API_TOKEN</CodeBlock><CodeBlock label="Accepted aliases">x-api-key: YOUR_API_TOKEN
Authorization: Bearer YOUR_API_TOKEN</CodeBlock><CodeBlock label="Auth error example">{`{ "status": "ERROR", "code": 120, "message": "API Token is required" }`}</CodeBlock></Section>
<Section id="profile" title="Profile"><Endpoint method="GET" path="/profile"><p>Returns the account’s current spendable balance and wallet currency.</p><CodeBlock label="Request">{request('/profile')}</CodeBlock><CodeBlock label="Successful response">{`{ "balance": "150", "email": "user@example.com", "currency": "USD" }`}</CodeBlock></Endpoint></Section>
<Section id="products" title="Products"><Endpoint method="GET" path="/products"><p>Lists products available to the authenticated reseller. Filter numeric IDs with <code>products_id</code>; <code>base=1</code> returns the legacy compact shape.</p><CodeBlock label="Request — catalog">{request('/products')}</CodeBlock><CodeBlock label="Request — selected IDs">{request('/products?products_id=1000,1001')}</CodeBlock><CodeBlock label="Request — compact">{request('/products?base=1')}</CodeBlock><CodeBlock label="Successful response">{product}</CodeBlock><CodeBlock label="base=1 response">{`[{ "id": 1000, "name": "Example package", "price": 1.5, "currency": "USD" }]`}</CodeBlock></Endpoint></Section>
<Section id="product-fields" title="Product Fields"><p><code>params</code> is the legacy label-only representation. New integrations must use canonical structured <code>fields[]</code>. Fixed/package products have <code>qty_values: null</code>; range products expose their existing <code>min</code>/<code>max</code> rules.</p><CodeBlock label="Structured field metadata">{`"fields": [{ "key": "player_id", "label": "Player ID", "type": "text", "required": true, "options": [] }]`}</CodeBlock></Section>
<Section id="content" title="Content / Categories"><Endpoint method="GET" path="/content/:parentId"><p>Use <code>0</code> for root content, or a numeric compatibility category ID for its children.</p><CodeBlock label="Request — root">{request('/content/0')}</CodeBlock><CodeBlock label="Response — root">{`{ "status": "OK", "data": { "categories": [{ "id": 7, "name": "Example category", "parent_id": 0, "available": true }], "products": [] } }`}</CodeBlock><CodeBlock label="Request — category">{request('/content/7')}</CodeBlock><CodeBlock label="Response — category">{`{ "status": "OK", "data": { "categories": [], "products": [{ "id": 1000, "name": "Example package", "price": 1.5, "currency": "USD" }] } }`}</CodeBlock></Endpoint></Section>
<Section id="create-order" title="Create Order"><Endpoint method="POST" path="/orders"><p>Do not send authoritative price, balance, or currency values. The server determines price and validates wallet rules. <code>order_uuid</code> is the stable idempotency key: replaying it for the same account does not debit twice.</p><CodeBlock label="Request">{`POST ${baseUrl}/orders
api-token: YOUR_API_TOKEN
Content-Type: application/json

{ "product_id": 1000, "qty": 1, "order_uuid": "stable-client-key", "params": { "player_id": "123456789" } }`}</CodeBlock><CodeBlock label="Successful response">{`{ "status": "OK", "data": { "order_id": "ID_0123456789abcdef", "order_uuid": "stable-client-key", "status": "wait", "price": 1.5, "currency": "USD", "data": { "player_id": "123456789" }, "replay_api": null } }`}</CodeBlock></Endpoint></Section>
<Section id="check-orders" title="Check Orders"><Endpoint method="GET" path="/check"><p>Only orders owned by the authenticated API account are returned.</p><CodeBlock label="Request — order IDs">{request('/check?orders=ID_1,ID_2')}</CodeBlock><CodeBlock label="Response — order IDs">{checkResponse}</CodeBlock><CodeBlock label="Request — legacy UUID lookup">{request('/check?orders=stable-client-key&uuid=1')}</CodeBlock><CodeBlock label="Response — legacy UUID lookup">{checkResponse}</CodeBlock><CodeBlock label="Request — canonical UUID lookup">{request('/check?uuids=stable-client-key')}</CodeBlock><CodeBlock label="Response — canonical UUID lookup">{checkResponse}</CodeBlock></Endpoint></Section>
<Section id="status-values" title="Status Values"><div className="grid gap-3 sm:grid-cols-3">{[['accept', 'Completed'], ['reject', 'Failed or canceled'], ['wait', 'Pending, processing, manual review, partial, or another in-flight state']].map(([status, meaning]) => <div key={status} className="rounded-xl border border-slate-700/70 bg-slate-950/35 p-4"><code className="font-mono font-bold text-amber-100">{status}</code><p className="mt-2 text-xs leading-5 text-slate-400">{meaning}</p></div>)}</div></Section>
<Section id="errors" title="Error Codes"><p>Compatibility failures use <code>{'{ "status": "ERROR", "code": number, "message": string }'}</code>.</p><CodeBlock label="Canonical error codes">100 insufficient balance    105 quantity unavailable    106 quantity not allowed
109 product not found       110 unavailable             111 rate limited
112 too small               113 too large               114 business rule
120 token required          121 invalid token           122 API disabled/inactive/blocked
123 IP not allowed          124 validation              130 maintenance
500 internal</CodeBlock><CodeBlock label="Validation error example">{`{ "status": "ERROR", "code": 124, "message": "params must be an object" }`}</CodeBlock></Section>
<Section id="code-examples" title="Code Examples"><CodeBlock label="cURL">{`curl -X POST ${baseUrl}/orders \\
  -H "api-token: YOUR_API_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"product_id":1000,"qty":1,"order_uuid":"stable-client-key","params":{"player_id":"123456789"}}'`}</CodeBlock><CodeBlock label="JavaScript">{`await fetch("${baseUrl}/orders", {
  method: "POST", headers: { "api-token": "YOUR_API_TOKEN", "Content-Type": "application/json" },
  body: JSON.stringify({ product_id: 1000, qty: 1, order_uuid: "stable-client-key", params: { player_id: "123456789" } }),
});`}</CodeBlock></Section>
<Section id="legacy" title="Legacy Compatibility"><Endpoint method="GET" path="/newOrder/:productId/params"><p>This route is compatibility-only. New integrations must use POST <code>/orders</code>. Its non-reserved query values become order field values; <code>qty</code> and <code>order_uuid</code> are required.</p><CodeBlock label="Legacy request">{request('/newOrder/1000/params?qty=1&player_id=123456789&order_uuid=stable-client-key')}</CodeBlock></Endpoint></Section>
</div></div></div></main>;
}
